### ISSUE TITLE
Application Crash when link generate

### ISSUE THREAD

**Issue by vishnunew** [blackmenthor/flutter-branch-io#31]
I am trying to generate link on Motorola Device. Tested Moto G Turbo and Moto G3. Application got crashed. Below is log. 

```
E/flutter (11039): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: com.anggach.flutterbranchioplugin.src.HandlerKt$generateLinkHandler$1
E/flutter (11039): 	at com.anggach.flutterbranchioplugin.src.HandlerKt.generateLinkHandler(Handler.kt:66)
E/flutter (11039): 	at com.anggach.flutterbranchioplugin.FlutterBranchIoPlugin.onMethodCall(FlutterBranchIoPlugin.kt:52)
E/flutter (11039): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (11039): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (11039): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (11039): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11039): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (11039): 	at android.os.Looper.loop(Looper.java:135)
E/flutter (11039): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
E/flutter (11039): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11039): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
E/flutter (11039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
E/flutter (11039): 
F/flutter (11039): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
```

Flutter version
```
Flutter 1.12.13+hotfix.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (2 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

**Comment by RodrigoSMarques** [comment]
Hi guys.
I don't know if it's the best solution. But as I was also facing some problems, I decided to create a new plugin.
If you want to test: https://pub.dev/packages/flutter_branch_sdk
I have applications published with this plugin

**Comment by RodrigoSMarques** [comment]
Hi @vishnunew 
I believe that this plugin is abandoned. There are many issues waiting to be answered.
See this here: https://pub.dev/packages/flutter_branch_sdk
